### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by flyingcatt3** [tony11306/Chiayi-university-system-api#2]
課表產生器和選課輔助器現在會產生錯誤

測試過在自己的電腦上run api，修改課表產生器的URL後按生成

然後flask server跳出這個錯誤，但校務行政系統沒掛掉
```
415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
[2023-05-01 06:08:55,917] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "c:\Users\jones\OneDrive\桌面\Chiayi-university-system-api-main\SchoolSystemModel\decorators.py", line 11, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jones\OneDrive\桌面\Chiayi-university-system-api-main\SchoolSystemModel\login.py", line 52, in post
    args = self.reqparse_args.parse_args()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_restful\reqparse.py", line 328, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_restful\reqparse.py", line 184, in parse
    source = self.source(request)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_restful\reqparse.py", line 125, in source
    value = getattr(request, l, None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\wrappers\request.py", line 565, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\wrappers\request.py", line 611, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\wrappers\request.py", line 654, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jones\OneDrive\桌面\Chiayi-university-system-api-main\SchoolSystemModel\decorators.py", line 20, in wrapper
    abort(500, {'result': 'unexpected error. It could be school system is under maintaining, or that page is unable to access currently.'})
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 277, in abort
    current_app.aborter(code, *args, **kwargs)
  File "C:\Users\jones\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: {'result': 'unexpected error. It could be school system is under maintaining, or that page is unable to access currently.'}
127.0.0.1 - - [01/May/2023 06:08:55] "POST /login HTTP/1.1" 500 -
```

**Comment by tony11306** [comment]
初步測試看起來 Azure 那邊 deployment 有點問題，晚點再看看

**Comment by tony11306** [comment]
現在確定 captcha 辨識有問題，學校貌似有稍微改動生成圖片的樣子(噪點的部分)，而我的 model 是有 over-fitting 的問題，導致辨識失敗一直回傳 error 500。

之前的 captcha
![2AGM](https://user-images.githubusercontent.com/50052865/235406098-6460abf3-e8a8-4e0b-9a4d-e070ea31dad5.png)

現在的 captcha
![ca](https://user-images.githubusercontent.com/50052865/235406188-e1e2769f-d224-49e1-ae0e-cf274981a722.png)


現在還有另一個問題，Azure 那邊的 app service 狀態變成了 AdminDisabled。這是比較奇怪的現象，billing 看起來正常，不知道是不是 error 太多次被 Azure security team 當成是在攻擊。

**Comment by tony11306** [comment]
Captcha 部分已經解決，增加資料集後重 train 一次就好。

Azure AdminDisabled 原因是我的 students 免費期限到了，接下來就要用愛發電了。

目前只剩個人課表 endpoint 有問題，本地端測試能正常運作，放在 Azure 就變成了 502 bad gateway 了。

**Comment by flyingcatt3** [comment]
更新model後在本地端run後error變成這樣：

```
ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "c:\Users\jones\OneDrive\桌面\project-course-rating\SchoolSystemModel\decorators.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\jones\OneDrive\桌面\project-course-rating\SchoolSystemModel\login.py", line 71, in post
    response = s.post(url=PRELOGIN_URL, headers={
KeyError: 'd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view 
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\Users\jones\OneDrive\桌面\project-course-rating\SchoolSystemModel\decorators.py", line 20, in wrapper   
    abort(500, {'result': 'unexpected error. It could be school system is under maintaining, or that page is unable to access currently.'})
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\exceptions.py", line 941, in abort
    _aborter(status, *args, **kwargs)
  File "C:\Users\jones\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\exceptions.py", line 924, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: {'result': 'unexpected error. It could be school system is under maintaining, or that page is unable to access currently.'}
127.0.0.1 - - [02/May/2023 05:57:19] "POST /login HTTP/1.1" 500 -
```

BTW, 這是在本地端用課表產生器產生的error
用python的requests call API就沒問題

**Comment by tony11306** [comment]
從你的錯誤來看是 login endpoint 的問題，在我 localhost 這部分是可以正常的運作。你可以試著看一下 response 的結果是什麼。

**Comment by flyingcatt3** [comment]
我改寫了login.py的這段程式碼
```py
response = s.post(url=PRELOGIN_URL, headers={
                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
                'content-type': 'application/json'
            }, json={
                'view':{
                    'AccountId': account,
                    'Password': password,
                    'Captcha': captcha_text
            }})
            #response=response.json()
print("debug")
for i in response:
	print(i)
print("debug")
```
結果:
```
debug
b'{"Message":"\xe8\x99\x95\xe7\x90\x86\xe6\xad\xa4\xe8\xa6\x81\xe6\xb1\x82\xe6\x99\x82\xe7\x99\xbc\xe7\x94\x9f\xe9\x8c\xaf\xe8\xaa\xa4\xe3\x80\x82","StackTrace":"","ExceptionType":""}'
debug
```
把上面的Message轉碼後得到`處理此要求時發生錯誤。`

不知道是不是user-agent的問題？

update:嘗試把帳號密碼寫死就正常了，不知道為甚麼抓不到網頁上填入的帳號密碼

**Comment by flyingcatt3** [comment]
問題已解決，自己沒搞懂flask的運作原理
